import type { RuleDefinition } from './types'

export const definitions: RuleDefinition[] = [
  {
    propertyNames: [
      "border-bottom-radius",
      "border-left-radius",
      "border-radius",
      "border-right-radius",
      "border-top-radius",
    ],
    separator: ':',    
    propertyValues: [
      { token: "0", propertyValue: "0px" },
      { token: "100", propertyValue: "2px" },
      { token: "200", propertyValue: "4px" },
      { token: "300", propertyValue: "6px" },
      { token: "400", propertyValue: "8px" },
      { token: "500", propertyValue: "16px" },
      { token: "600", propertyValue: "32px" },
      { token: "700", propertyValue: "64px" },
      { token: "800", propertyValue: "128px" },
      { token: "900", propertyValue: "256px" },
      { token: "1000", propertyValue: "512px" },
    ],
  },
  {
    propertyNames: [
      "border-bottom-width",
      "border-left-width",
      "border-width",
      "border-right-width",
      "border-top-width",      
    ],
    separator: ':',
    propertyValues: [
      { token: "0", propertyValue: "0" },
      { token: "100", propertyValue: "1" },
      { token: "200", propertyValue: "2" },
      { token: "300", propertyValue: "4" },
      { token: "400", propertyValue: "8" },
    ],
  },
  {
    propertyNames: [
      "background-color",
      "background-color-bottom",
      "background-color-left",
      "background-color-right",
      "background-color-top",
      "border-bottom-color",
      "border-color",
      "border-left-color",
      "border-right-color",
      "border-top-color",
      "color",
    ],    
    separator: ':',   
    propertyValues: [
        {
          propertyNames: ['neutral'],
          separator: '-',
          propertyValues: [
            { token: "50", propertyValue: "hsl(220, 25%, 97.5%)" },
            { token: "100", propertyValue: "hsl(220, 25%, 95%)" },
            { token: "200", propertyValue: "hsl(220, 25%, 85%)" },
            { token: "300", propertyValue: "hsl(220, 25%, 75%)" },
            { token: "400", propertyValue: "hsl(220, 25%, 65%)" },
            { token: "500", propertyValue: "hsl(220, 25%, 50%)" },
            { token: "600", propertyValue: "hsl(220, 25%, 40%)" },
            { token: "700", propertyValue: "hsl(220, 25%, 30%)" },
            { token: "800", propertyValue: "hsl(220, 25%, 20%)" },
            { token: "900", propertyValue: "hsl(220, 25%, 15%)" },
          ],
        },
        {
          propertyNames: ['red'],
          separator: '-',
          propertyValues: [
            { token: "50", propertyValue: "hsl(0, 100%, 97.5%)" },
            { token: "100", propertyValue: "hsl(0, 100%, 95%)" },
            { token: "200", propertyValue: "hsl(0, 100%, 85%)" },
            { token: "300", propertyValue: "hsl(0, 100%, 75%)" },
            { token: "400", propertyValue: "hsl(0, 100%, 65%)" },
            { token: "500", propertyValue: "hsl(0, 100%, 35%)" },
            { token: "600", propertyValue: "hsl(0, 100%, 30%)" },
            { token: "700", propertyValue: "hsl(0, 100%, 25%)" },
            { token: "800", propertyValue: "hsl(0, 100%, 20%)" },
            { token: "900", propertyValue: "hsl(0, 100%, 15%)" },
          ],
        },
        {
          propertyNames: ['orange'],
          separator: '-',
          propertyValues: [
            { token: "50", propertyValue: "hsl(25, 100%, 97.5%)" },
            { token: "100", propertyValue: "hsl(25, 100%, 95%)" },
            { token: "200", propertyValue: "hsl(25, 100%, 85%)" },
            { token: "300", propertyValue: "hsl(25, 100%, 75%)" },
            { token: "400", propertyValue: "hsl(25, 100%, 60%)" },
            { token: "500", propertyValue: "hsl(25, 100%, 50%)" },
            { token: "600", propertyValue: "hsl(25, 100%, 40%)" },
            { token: "700", propertyValue: "hsl(25, 100%, 35%)" },
            { token: "800", propertyValue: "hsl(25, 100%, 25%)" },
            { token: "900", propertyValue: "hsl(25, 100%, 20%)" },    
          ],
        },
        {
          propertyNames: ['yellow'],
          separator: '-',
          propertyValues: [
            { token: "50", propertyValue: "hsl(50, 100%, 97.5%)" },
            { token: "100", propertyValue: "hsl(50, 100%, 95%)" },
            { token: "200", propertyValue: "hsl(50, 100%, 85%)" },
            { token: "300", propertyValue: "hsl(50, 100%, 75%)" },
            { token: "400", propertyValue: "hsl(50, 100%, 60%)" },
            { token: "500", propertyValue: "hsl(50, 100%, 50%)" },
            { token: "600", propertyValue: "hsl(50, 100%, 40%)" },
            { token: "700", propertyValue: "hsl(50, 100%, 35%)" },
            { token: "800", propertyValue: "hsl(50, 100%, 25%)" },
            { token: "900", propertyValue: "hsl(50, 100%, 20%)" },
          ],
        },
        {
          propertyNames: ['green'],
          separator: '-',
          propertyValues: [
            { token: "50", propertyValue: "hsl(135, 80%, 97.5%)" },
            { token: "100", propertyValue: "hsl(135, 80%, 95%)" },
            { token: "200", propertyValue: "hsl(135, 80%, 85%)" },
            { token: "300", propertyValue: "hsl(135, 80%, 75%)" },
            { token: "400", propertyValue: "hsl(135, 80%, 45%)" },
            { token: "500", propertyValue: "hsl(135, 80%, 35%)" },
            { token: "600", propertyValue: "hsl(135, 80%, 30%)" },
            { token: "700", propertyValue: "hsl(135, 80%, 25%)" },
            { token: "800", propertyValue: "hsl(135, 80%, 20%)" },
            { token: "900", propertyValue: "hsl(135, 80%, 15%)" },
          ],
        },
        {
          propertyNames: ['teal'],
          separator: '-',
          propertyValues: [
            { token: "50", propertyValue: "hsl(180, 80%, 97.5%)" },
            { token: "100", propertyValue: "hsl(180, 80%, 95%)" },
            { token: "200", propertyValue: "hsl(180, 80%, 85%)" },
            { token: "300", propertyValue: "hsl(180, 80%, 75%)" },
            { token: "400", propertyValue: "hsl(180, 80%, 45%)" },
            { token: "500", propertyValue: "hsl(180, 80%, 35%)" },
            { token: "600", propertyValue: "hsl(180, 80%, 30%)" },
            { token: "700", propertyValue: "hsl(180, 80%, 25%)" },
            { token: "800", propertyValue: "hsl(180, 80%, 20%)" },
            { token: "900", propertyValue: "hsl(180, 80%, 15%)" },    
          ],
        },
        {
          propertyNames: ['blue'],
          separator: '-',
          propertyValues: [
            { token: "50", propertyValue: "hsl(220, 80%, 97.5%)" },
            { token: "100", propertyValue: "hsl(220, 80%, 95%)" },
            { token: "200", propertyValue: "hsl(220, 80%, 85%)" },
            { token: "300", propertyValue: "hsl(220, 80%, 75%)" },
            { token: "400", propertyValue: "hsl(220, 80%, 65%)" },
            { token: "500", propertyValue: "hsl(220, 80%, 50%)" },
            { token: "600", propertyValue: "hsl(220, 80%, 40%)" },
            { token: "700", propertyValue: "hsl(220, 80%, 35%)" },
            { token: "800", propertyValue: "hsl(220, 80%, 30%)" },
            { token: "900", propertyValue: "hsl(220, 80%, 20%)" },
          ],
        },
        {
          propertyNames: ['purple'],
          separator: '-',
          propertyValues: [
            { token: "50", propertyValue: "hsl(280, 80%, 97.5%)" },
            { token: "100", propertyValue: "hsl(280, 80%, 95%)" },
            { token: "200", propertyValue: "hsl(280, 80%, 85%)" },
            { token: "300", propertyValue: "hsl(280, 80%, 75%)" },
            { token: "400", propertyValue: "hsl(280, 80%, 65%)" },
            { token: "500", propertyValue: "hsl(280, 80%, 50%)" },
            { token: "600", propertyValue: "hsl(280, 80%, 40%)" },
            { token: "700", propertyValue: "hsl(280, 80%, 35%)" },
            { token: "800", propertyValue: "hsl(280, 80%, 30%)" },
            { token: "900", propertyValue: "hsl(280, 80%, 20%)" },
          ],
        },
        {
          propertyNames: ['pink'],
          separator: '-',
          propertyValues: [
            { token: "50", propertyValue: "hsl(320, 80%, 97.5%)" },
            { token: "100", propertyValue: "hsl(320, 80%, 95%)" },
            { token: "200", propertyValue: "hsl(320, 80%, 85%)" },
            { token: "300", propertyValue: "hsl(320, 80%, 75%)" },
            { token: "400", propertyValue: "hsl(320, 80%, 65%)" },
            { token: "500", propertyValue: "hsl(320, 80%, 50%)" },
            { token: "600", propertyValue: "hsl(320, 80%, 40%)" },
            { token: "700", propertyValue: "hsl(320, 80%, 35%)" },
            { token: "800", propertyValue: "hsl(320, 80%, 30%)" },
            { token: "900", propertyValue: "hsl(320, 80%, 20%)" },
          ],
        },
      ]
    },
  {
    propertyNames: [
      "font-size",
    ],
    separator: ':',
    propertyValues: [
      { token: "100", propertyValue: "0.5rem" },
      { token: "200", propertyValue: "0.625rem" },
      { token: "300", propertyValue: "0.75rem" },
      { token: "400", propertyValue: "0.875rem" },
      { token: "500", propertyValue: "1rem" },
      { token: "600", propertyValue: "1.125rem" },
      { token: "700", propertyValue: "1.25rem" },
      { token: "800", propertyValue: "1.5rem" },
      { token: "900", propertyValue: "2rem" },
    ],
  },
  {
    propertyNames: [
      "font-weight",
    ],
    separator: ':',
    propertyValues: [
      { token: "100", propertyValue: "100" },
      { token: "200", propertyValue: "200" },
      { token: "300", propertyValue: "300" },
      { token: "400", propertyValue: "400" },
      { token: "500", propertyValue: "500" },
      { token: "600", propertyValue: "600" },
      { token: "700", propertyValue: "700" },
      { token: "800", propertyValue: "800" },
      { token: "900", propertyValue: "900" },
    ]
  },
  {
    propertyNames: [
      "gap",
      "column-gap",
      "row-gap",
    ],
    separator: ':',
    propertyValues: [
      { token: "0", propertyValue: "0px" },
      { token: "100", propertyValue: "2px" },
      { token: "200", propertyValue: "4px" },
      { token: "300", propertyValue: "8px" },
      { token: "400", propertyValue: "16px" },
      { token: "500", propertyValue: "32px" },
      { token: "600", propertyValue: "64px" },
      { token: "700", propertyValue: "128px" },
      { token: "800", propertyValue: "192px" },
      { token: "900", propertyValue: "256px" },
      { token: "1000", propertyValue: "512px" },
    ],
  },
  {
    propertyNames: [
      "height",
      "max-height",
      "min-height",
    ],
    separator: ':',
    propertyValues: [
      { token: "0",propertyValue: "0" },
      { token: "100", propertyValue: "0.625rem" },
      { token: "200", propertyValue: "0.75rem" },
      { token: "100\\%", propertyValue: "100%" },
      { token: "100vh", propertyValue: "100vh" },
      { token: "none", propertyValue: "none" },
    ]
  },
  {
    propertyNames: [
      "line-height",
    ],
    separator: ':',
    propertyValues: [
      { token: "100", propertyValue: "1" },
      { token: "200", propertyValue: "1.25" },
      { token: "300", propertyValue: "1.375" },
      { token: "400", propertyValue: "1.5" },
      { token: "500", propertyValue: "1.625" },
      { token: "600", propertyValue: "1.75" },
      { token: "700", propertyValue: "2" },
    ],
  },
  {
    propertyNames: [
      "margin",
      "margin-bottom",
      "margin-horizontal",
      "margin-left",
      "margin-right",
      "margin-top",
      "margin-vertical",
    ],
    separator: ':',
    propertyValues: [
      { token: "0", propertyValue: "0px" },
      { token: "100", propertyValue: "2px" },
      { token: "200", propertyValue: "4px" },
      { token: "300", propertyValue: "6px" },
      { token: "400", propertyValue: "8px" },
      { token: "500", propertyValue: "16px" },
      { token: "600", propertyValue: "32px" },
      { token: "700", propertyValue: "64px" },
      { token: "800", propertyValue: "128px" },
      { token: "900", propertyValue: "256px" },
      { token: "1000", propertyValue: "512px" },
      { token: "auto", propertyValue: "auto" },
    ],
  },
  {
    propertyNames: [
      "opacity",
    ],
    separator: ':',
    propertyValues: [
      { token: "0", propertyValue: "0%" },
      { token: "10", propertyValue: "10%" },
      { token: "20", propertyValue: "20%" },
      { token: "30", propertyValue: "30%" },
      { token: "40", propertyValue: "40%" },
      { token: "50", propertyValue: "50%" },
      { token: "60", propertyValue: "60%" },
      { token: "70", propertyValue: "70%" },
      { token: "80", propertyValue: "80%" },
      { token: "90", propertyValue: "90%" },
      { token: "100", propertyValue: "100%" },
    ],
  },
  {
    propertyNames: [
      "padding",
      "padding-bottom",
      "padding-horizontal",
      "padding-left",
      "padding-right",
      "padding-top",
      "padding-vertical",
    ],
    separator: ':',
    propertyValues: [
      { token: "0", propertyValue: "0px" },
      { token: "100", propertyValue: "2px" },
      { token: "200", propertyValue: "4px" },
      { token: "300", propertyValue: "6px" },
      { token: "400", propertyValue: "8px" },
      { token: "500", propertyValue: "16px" },
      { token: "600", propertyValue: "32px" },
      { token: "700", propertyValue: "64px" },
      { token: "800", propertyValue: "128px" },
      { token: "900", propertyValue: "256px" },
      { token: "1000", propertyValue: "512px" },
      { token: "auto", propertyValue: "auto" },
    ],
  },
  {
    propertyNames: [
      "max-width",
      "min-width",
      "width",
    ],
    separator: ':',
    propertyValues: [
      { token: "0", propertyValue: "0" },
      { token: "5\\%", propertyValue: "5%" },
      { token: "10\\%", propertyValue: "10%" },
      { token: "16\\.6\\%", propertyValue: "16.66667%" },
      { token: "20\\%", propertyValue: "20%" },
      { token: "25\\%", propertyValue: "25%" },
      { token: "30\\%", propertyValue: "30%" },
      { token: "33\\.3\\%", propertyValue: "33.33333%" },
      { token: "40\\%", propertyValue: "40%" },
      { token: "50\\%", propertyValue: "50%" },
      { token: "60\\%", propertyValue: "60%" },
      { token: "66\\.6\\%", propertyValue: "66.66666%" },
      { token: "70\\%", propertyValue: "70%" },
      { token: "75\\%", propertyValue: "75%" },
      { token: "80\\%", propertyValue: "80%" },
      { token: "83\\.3\\%", propertyValue: "83.33333%" },
      { token: "90\\%", propertyValue: "90%" },
      { token: "100\\%", propertyValue: "100%" },
      { token: "100vw", propertyValue: "100vw" },
      { token: "auto", propertyValue: "auto" },
    ],
  },
]
