export interface BaseCSSDeclarations {
  property: string;
  values: string[];
}


const declarations: BaseCSSDeclarations[] = [
  {
    property: "direction",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "ltr",
      "rtl",
    ]
  },
  {
    property: "display",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "inline",
      "block",
      "flow",
      "flow-root",
      "list-item",
      "compact",
      "inline-block",
      "run-in",
      "table",
      "inline-table",
      "table-row-group",
      "table-header-group",
      "table-footer-group",
      "table-row",
      "table-column-group",
      "table-column",
      "table-cell",
      "table-caption",
      "-webkit-box",
      "-webkit-inline-box",
      "flex",
      "-webkit-flex",
      "inline-flex",
      "-webkit-inline-flex",
      "contents",
      "none",
      "grid",
      "inline-grid",
    ]
  },
  {
    property: "font-style",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "normal",
      "italic",
      "oblique",
    ]
  },
  {
    property: "font-stretch",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "normal",
      "ultra-condensed",
      "extra-condensed",
      "condensed",
      "semi-condensed",
      "semi-expanded",
      "expanded",
      "extra-expanded",
      "ultra-expanded",
    ]
  },
  {
    property: "text-rendering",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "optimizespeed",
      "optimizelegibility",
      "geometricprecision",
    ]
  },
  {
    property: "-webkit-font-kerning",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "normal",
      "none",
    ]
  },
  {
    property: "-webkit-font-smoothing",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "none",
      "antialiased",
      "subpixel-antialiased",
    ]
  },
  {
    property: "font-variant-position",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "normal",
      "sub",
      "super",
    ]
  },
  {
    property: "font-variant-caps",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "normal",
      "small-caps",
      "all-small-caps",
      "petite-caps",
      "all-petite-caps",
      "unicase",
      "titling-caps",
    ]
  },
  {
    property: "font-variant-alternates",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "normal",
      "historical-forms",
    ]
  },
  {
    property: "font-optical-sizing",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "none",
    ]
  },
  {
    property: "text-orientation",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "sideways",
      "mixed",
      "upright",
    ]
  },
  {
    property: "-webkit-text-orientation",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "sideways",
      "mixed",
      "upright",
    ]
  },
  {
    property: "writing-mode",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "horizontal-tb",
      "vertical-rl",
      "vertical-lr",
      "sideways-rl",
      "sideways-lr",
    ]
  },
  {
    property: "-webkit-text-zoom",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "normal",
      "reset",
    ]
  },
  {
    property: "-webkit-ruby-position",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "inter-character",
      "over",
      "under",
    ]
  },
  {
    property: "alignment-baseline",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "baseline",
      "middle",
      "before-edge",
      "after-edge",
      "central",
      "text-before-edge",
      "text-after-edge",
      "ideographic",
      "hanging",
      "mathematical",
    ]
  },
  {
    property: "animation-direction",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "normal",
      "reverse",
      "alternate",
      "alternate-reverse",
    ]
  },
  {
    property: "animation-fill-mode",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "forwards",
      "backwards",
      "both",
    ]
  },
  {
    property: "animation-play-state",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "running",
      "paused",
    ]
  },
  {
    property: "background-attachment",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "fixed",
      "local",
      "scroll",
    ]
  },
  {
    property: "background-blend-mode",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "normal",
      "multiply",
      "screen",
      "overlay",
      "darken",
      "lighten",
      "color-dodge",
      "color-burn",
      "hard-light",
      "soft-light",
      "difference",
      "exclusion",
      "hue",
      "saturation",
      "color",
      "luminosity",
    ]
  },
  {
    property: "background-clip",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "border-box",
      "padding-box",
      "content-box",
    ]
  },
  {
    property: "border-block-end-style",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "none",
      "hidden",
      "inset",
      "groove",
      "outset",
      "ridge",
      "dotted",
      "dashed",
      "solid",
      "double",
    ]
  },
  {
    property: "border-block-start-style",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "none",
      "hidden",
      "inset",
      "groove",
      "outset",
      "ridge",
      "dotted",
      "dashed",
      "solid",
      "double",
    ]
  },
  {
    property: "border-bottom-style",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "none",
      "hidden",
      "inset",
      "groove",
      "outset",
      "ridge",
      "dotted",
      "dashed",
      "solid",
      "double",
    ]
  },
  {
    property: "border-collapse",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "collapse",
      "separate",
    ]
  },
  {
    property: "border-inline-end-style",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "none",
      "hidden",
      "inset",
      "groove",
      "outset",
      "ridge",
      "dotted",
      "dashed",
      "solid",
      "double",
    ]
  },
  {
    property: "border-inline-start-style",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "none",
      "hidden",
      "inset",
      "groove",
      "outset",
      "ridge",
      "dotted",
      "dashed",
      "solid",
      "double",
    ]
  },
  {
    property: "border-left-style",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "none",
      "hidden",
      "inset",
      "groove",
      "outset",
      "ridge",
      "dotted",
      "dashed",
      "solid",
      "double",
    ]
  },
  {
    property: "border-right-style",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "none",
      "hidden",
      "inset",
      "groove",
      "outset",
      "ridge",
      "dotted",
      "dashed",
      "solid",
      "double",
    ]
  },
  {
    property: "border-top-style",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "none",
      "hidden",
      "inset",
      "groove",
      "outset",
      "ridge",
      "dotted",
      "dashed",
      "solid",
      "double",
    ]
  },
  {
    property: "box-sizing",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "border-box",
      "content-box",
    ]
  },
  {
    property: "break-after",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "avoid",
      "left",
      "right",
      "recto",
      "verso",
      "column",
      "page",
      "avoid-column",
      "avoid-page",
    ]
  },
  {
    property: "break-before",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "avoid",
      "left",
      "right",
      "recto",
      "verso",
      "column",
      "page",
      "avoid-column",
      "avoid-page",
    ]
  },
  {
    property: "break-inside",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "avoid",
      "avoid-column",
      "avoid-page",
    ]
  },
  {
    property: "buffered-rendering",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "dynamic",
      "static",
    ]
  },
  {
    property: "caption-side",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "left",
      "right",
      "top",
      "bottom",
    ]
  },
  {
    property: "clear",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "none",
      "left",
      "right",
      "both",
    ]
  },
  {
    property: "clip-rule",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "nonzero",
      "evenodd",
    ]
  },
  {
    property: "color-interpolation",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "srgb",
      "linearrgb",
    ]
  },
  {
    property: "color-interpolation-filters",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "srgb",
      "linearrgb",
    ]
  },
  {
    property: "color-rendering",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "optimizespeed",
      "optimizequality",
    ]
  },
  {
    property: "cursor",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "context-menu",
      "help",
      "pointer",
      "progress",
      "wait",
      "cell",
      "crosshair",
      "text",
      "vertical-text",
      "alias",
      "copy",
      "move",
      "no-drop",
      "not-allowed",
      "grab",
      "grabbing",
      "e-resize",
      "n-resize",
      "ne-resize",
      "nw-resize",
      "s-resize",
      "se-resize",
      "sw-resize",
      "w-resize",
      "ew-resize",
      "ns-resize",
      "nesw-resize",
      "nwse-resize",
      "col-resize",
      "row-resize",
      "all-scroll",
      "zoom-in",
      "zoom-out",
    ]
  },
  {
    property: "-webkit-cursor-visibility",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "auto-hide",
    ]
  },
  {
    property: "dominant-baseline",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "middle",
      "use-script",
      "no-change",
      "reset-size",
      "central",
      "text-before-edge",
      "text-after-edge",
      "ideographic",
      "hanging",
      "mathematical",
    ]
  },
  {
    property: "empty-cells",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "show",
      "hide",
    ]
  },
  {
    property: "fill-rule",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "nonzero",
      "evenodd",
    ]
  },
  {
    property: "float",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "left",
      "right",
      "none",
    ]
  },
  {
    property: "image-rendering",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "optimizespeed",
      "optimizequality",
      "crisp-edges",
      "pixelated",
    ]
  },
  {
    property: "list-style-position",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "inside",
      "outside",
    ]
  },
  {
    property: "list-style-type",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "disc",
      "circle",
      "square",
      "decimal",
      "decimal-leading-zero",
      "arabic-indic",
      "binary",
      "bengali",
      "cambodian",
      "khmer",
      "devanagari",
      "gujarati",
      "gurmukhi",
      "kannada",
      "lower-hexadecimal",
      "lao",
      "malayalam",
      "mongolian",
      "myanmar",
      "octal",
      "oriya",
      "persian",
      "urdu",
      "telugu",
      "tibetan",
      "thai",
      "upper-hexadecimal",
      "lower-roman",
      "upper-roman",
      "lower-greek",
      "lower-alpha",
      "lower-latin",
      "upper-alpha",
      "upper-latin",
      "afar",
      "ethiopic-halehame-aa-et",
      "ethiopic-halehame-aa-er",
      "amharic",
      "ethiopic-halehame-am-et",
      "amharic-abegede",
      "ethiopic-abegede-am-et",
      "cjk-earthly-branch",
      "cjk-heavenly-stem",
      "ethiopic",
      "ethiopic-halehame-gez",
      "ethiopic-abegede",
      "ethiopic-abegede-gez",
      "hangul-consonant",
      "hangul",
      "lower-norwegian",
      "oromo",
      "ethiopic-halehame-om-et",
      "sidama",
      "ethiopic-halehame-sid-et",
      "somali",
      "ethiopic-halehame-so-et",
      "tigre",
      "ethiopic-halehame-tig",
      "tigrinya-er",
      "ethiopic-halehame-ti-er",
      "tigrinya-er-abegede",
      "ethiopic-abegede-ti-er",
      "tigrinya-et",
      "ethiopic-halehame-ti-et",
      "tigrinya-et-abegede",
      "ethiopic-abegede-ti-et",
      "upper-greek",
      "upper-norwegian",
      "asterisks",
      "footnotes",
      "hebrew",
      "armenian",
      "lower-armenian",
      "upper-armenian",
      "georgian",
      "cjk-ideographic",
      "hiragana",
      "katakana",
      "hiragana-iroha",
      "katakana-iroha",
      "none",
    ]
  },
  {
    property: "mask-type",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "luminance",
      "alpha",
    ]
  },
  {
    property: "math-style",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "normal",
      "compact",
    ]
  },
  {
    property: "object-fit",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "fill",
      "contain",
      "cover",
      "none",
      "scale-down",
    ]
  },
  {
    property: "outline-style",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "none",
      "inset",
      "groove",
      "outset",
      "ridge",
      "dotted",
      "dashed",
      "solid",
      "double",
    ]
  },
  {
    property: "overflow-wrap",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "normal",
      "break-word",
    ]
  },
  {
    property: "overflow-x",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "visible",
      "hidden",
      "scroll",
      "auto",
    ]
  },
  {
    property: "overflow-y",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "visible",
      "hidden",
      "scroll",
      "auto",
      "-webkit-paged-x",
      "-webkit-paged-y",
    ]
  },
  {
    property: "overscroll-behavior-x",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "contain",
      "none",
      "auto",
    ]
  },
  {
    property: "overscroll-behavior-y",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "contain",
      "none",
      "auto",
    ]
  },
  {
    property: "pointer-events",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "visible",
      "none",
      "all",
      "auto",
      "visiblepainted",
      "visiblefill",
      "visiblestroke",
      "painted",
      "fill",
      "stroke",
      "bounding-box",
    ]
  },
  {
    property: "position",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "static",
      "relative",
      "absolute",
      "fixed",
      "sticky",
    ]
  },
  {
    property: "resize",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "none",
      "both",
      "horizontal",
      "vertical",
      "auto",
    ]
  },
  {
    property: "shape-rendering",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "optimizespeed",
      "crispedges",
      "geometricprecision",
    ]
  },
  {
    property: "stroke-linecap",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "butt",
      "round",
      "square",
    ]
  },
  {
    property: "stroke-linejoin",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "miter",
      "round",
      "bevel",
    ]
  },
  {
    property: "table-layout",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "fixed",
    ]
  },
  {
    property: "text-align",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "left",
      "right",
      "center",
      "justify",
      "-webkit-left",
      "-webkit-right",
      "-webkit-center",
      "-webkit-match-parent",
      "start",
      "end",
    ]
  },
  {
    property: "text-anchor",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "start",
      "middle",
      "end",
    ]
  },
  {
    property: "text-decoration",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "underline",
      "overline",
      "line-through",
    ]
  },
  {
    property: "text-line-through-mode",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "continuous",
      "skip-white-space",
    ]
  },
  {
    property: "text-line-through-style",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "none",
      "solid",
      "double",
      "dashed",
      "dot-dash",
      "dot-dot-dash",
      "wave",
    ]
  },
  {
    property: "text-overflow",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "clip",
      "ellipsis",
    ]
  },
  {
    property: "text-overline-mode",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "continuous",
      "skip-white-space",
    ]
  },
  {
    property: "text-overline-style",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "none",
      "solid",
      "double",
      "dashed",
      "dot-dash",
      "dot-dot-dash",
      "wave",
    ]
  },
  {
    property: "text-transform",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "capitalize",
      "uppercase",
      "lowercase",
      "none",
    ]
  },
  {
    property: "text-underline-mode",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "continuous",
      "skip-white-space",
    ]
  },
  {
    property: "text-underline-style",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "none",
      "solid",
      "double",
      "dashed",
      "dot-dash",
      "dot-dot-dash",
      "wave",
    ]
  },
  {
    property: "unicode-bidi",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "normal",
      "embed",
      "bidi-override",
      "isolate",
      "isolate-override",
      "plaintext",
    ]
  },
  {
    property: "font-display",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "block",
      "swap",
      "fallback",
      "optional",
    ]
  },
  {
    property: "vector-effect",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "none",
      "non-scaling-stroke",
    ]
  },
  {
    property: "visibility",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "visible",
      "hidden",
      "collapse",
    ]
  },
  {
    property: "white-space",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "normal",
      "pre",
      "pre-wrap",
      "pre-line",
      "nowrap",
      "break-spaces",
    ]
  },
  {
    property: "word-break",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "normal",
      "break-all",
      "keep-all",
      "break-word",
    ]
  },
  {
    property: "word-wrap",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "normal",
      "break-word",
    ]
  },
  {
    property: "-webkit-appearance",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "checkbox",
      "radio",
      "push-button",
      "square-button",
      "button",
      "button-bevel",
      "default-button",
      "inner-spin-button",
      "listbox",
      "listitem",
      "media-controls-background",
      "media-controls-dark-bar-background",
      "media-controls-fullscreen-background",
      "media-controls-light-bar-background",
      "media-current-time-display",
      "media-enter-fullscreen-button",
      "media-exit-fullscreen-button",
      "media-fullscreen-volume-slider",
      "media-fullscreen-volume-slider-thumb",
      "media-mute-button",
      "media-overlay-play-button",
      "media-play-button",
      "media-return-to-realtime-button",
      "media-rewind-button",
      "media-seek-back-button",
      "media-seek-forward-button",
      "media-slider",
      "media-sliderthumb",
      "media-time-remaining-display",
      "media-toggle-closed-captions-button",
      "media-volume-slider",
      "media-volume-slider-container",
      "media-volume-slider-mute-button",
      "media-volume-sliderthumb",
      "menulist",
      "menulist-button",
      "menulist-text",
      "menulist-textfield",
      "meter",
      "progress-bar",
      "progress-bar-value",
      "slider-horizontal",
      "slider-vertical",
      "sliderthumb-horizontal",
      "sliderthumb-vertical",
      "caret",
      "searchfield",
      "searchfield-decoration",
      "searchfield-results-decoration",
      "searchfield-results-button",
      "searchfield-cancel-button",
      "snapshotted-plugin-overlay",
      "textfield",
      "relevancy-level-indicator",
      "continuous-capacity-level-indicator",
      "discrete-capacity-level-indicator",
      "rating-level-indicator",
      "image-controls-button",
      "-apple-pay-button",
      "textarea",
      "attachment",
      "caps-lock-indicator",
      "color-well",
      "list-button",
      "none",
    ]
  },
  {
    property: "-webkit-backface-visibility",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "visible",
      "hidden",
    ]
  },
  {
    property: "-webkit-background-composite",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "clear",
      "copy",
      "source-over",
      "source-in",
      "source-out",
      "source-atop",
      "destination-over",
      "destination-in",
      "destination-out",
      "destination-atop",
      "xor",
      "plus-darker",
      "highlight",
      "plus-lighter",
    ]
  },
  {
    property: "-webkit-border-fit",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "border",
      "lines",
    ]
  },
  {
    property: "-webkit-box-align",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "stretch",
      "start",
      "end",
      "center",
      "baseline",
    ]
  },
  {
    property: "-webkit-box-direction",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "normal",
      "reverse",
    ]
  },
  {
    property: "-webkit-box-lines",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "single",
      "multiple",
    ]
  },
  {
    property: "-webkit-box-orient",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "horizontal",
      "vertical",
      "inline-axis",
      "block-axis",
    ]
  },
  {
    property: "-webkit-box-pack",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "start",
      "end",
      "center",
      "justify",
    ]
  },
  {
    property: "-webkit-column-axis",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "horizontal",
      "vertical",
      "auto",
    ]
  },
  {
    property: "column-fill",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "balance",
    ]
  },
  {
    property: "-webkit-column-progression",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "normal",
      "reverse",
    ]
  },
  {
    property: "column-rule-style",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "none",
      "hidden",
      "inset",
      "groove",
      "outset",
      "ridge",
      "dotted",
      "dashed",
      "solid",
      "double",
    ]
  },
  {
    property: "-webkit-box-decoration-break",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "clone",
      "slice",
    ]
  },
  {
    property: "mix-blend-mode",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "normal",
      "multiply",
      "screen",
      "overlay",
      "darken",
      "lighten",
      "color-dodge",
      "color-burn",
      "hard-light",
      "soft-light",
      "difference",
      "exclusion",
      "plus-darker",
      "plus-lighter",
    ]
  },
  {
    property: "isolation",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "isolate",
    ]
  },
  {
    property: "align-content",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "flex-start",
      "flex-end",
      "center",
      "space-between",
      "space-around",
      "stretch",
    ]
  },
  {
    property: "align-items",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "flex-start",
      "flex-end",
      "center",
      "baseline",
      "stretch",
    ]
  },
  {
    property: "align-self",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "flex-start",
      "flex-end",
      "center",
      "baseline",
      "stretch",
    ]
  },
  {
    property: "flex-direction",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "row",
      "row-reverse",
      "column",
      "column-reverse",
    ]
  },
  {
    property: "flex-wrap",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "nowrap",
      "wrap",
      "wrap-reverse",
    ]
  },
  {
    property: "justify-content",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "flex-start",
      "flex-end",
      "center",
      "space-between",
      "space-around",
    ]
  },
  {
    property: "-webkit-hyphens",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "none",
      "manual",
      "auto",
    ]
  },
  {
    property: "-webkit-line-box-contain",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "block",
      "inline",
      "font",
      "glyphs",
      "replaced",
      "inline-box",
      "initial-letter",
    ]
  },
  {
    property: "-webkit-line-align",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "none",
      "edges",
    ]
  },
  {
    property: "line-break",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "loose",
      "normal",
      "strict",
      "anywhere",
    ]
  },
  {
    property: "-webkit-line-snap",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "none",
      "baseline",
      "contain",
    ]
  },
  {
    property: "-webkit-box-snap",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "block-start",
      "block-end",
      "center",
      "first-baseline",
      "last-baseline",
    ]
  },
  {
    property: "-webkit-margin-after-collapse",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "collapse",
      "separate",
      "discard",
    ]
  },
  {
    property: "-webkit-margin-before-collapse",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "collapse",
      "separate",
      "discard",
    ]
  },
  {
    property: "-webkit-margin-bottom-collapse",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "collapse",
      "separate",
      "discard",
    ]
  },
  {
    property: "-webkit-margin-top-collapse",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "collapse",
      "separate",
      "discard",
    ]
  },
  {
    property: "-webkit-marquee-direction",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "forwards",
      "backwards",
      "ahead",
      "reverse",
      "left",
      "right",
      "down",
      "up",
      "auto",
    ]
  },
  {
    property: "-webkit-marquee-style",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "none",
      "slide",
      "scroll",
      "alternate",
    ]
  },
  {
    property: "-webkit-nbsp-mode",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "normal",
      "space",
    ]
  },
  {
    property: "color-scheme",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "light",
      "dark",
      "only",
    ]
  },
  {
    property: "-webkit-print-color-adjust",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "exact",
      "economy",
    ]
  },
  {
    property: "-webkit-rtl-ordering",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "logical",
      "visual",
    ]
  },
  {
    property: "-webkit-text-combine",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "none",
      "horizontal",
    ]
  },
  {
    property: "-webkit-text-align-last",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "left",
      "right",
      "center",
      "justify",
      "start",
      "end",
      "auto",
    ]
  },
  {
    property: "-webkit-text-justify",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "inter-word",
      "distribute",
      "auto",
      "none",
    ]
  },
  {
    property: "text-decoration-style",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "solid",
      "double",
      "dotted",
      "dashed",
      "wavy",
    ]
  },
  {
    property: "-webkit-text-security",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "disc",
      "circle",
      "square",
      "none",
    ]
  },
  {
    property: "transform-box",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "content-box",
      "border-box",
      "fill-box",
      "stroke-box",
      "view-box",
    ]
  },
  {
    property: "transform-style",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "flat",
      "preserve-3d",
    ]
  },
  {
    property: "-webkit-transform-style",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "flat",
      "preserve-3d",
    ]
  },
  {
    property: "-webkit-user-drag",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "none",
      "element",
    ]
  },
  {
    property: "-webkit-user-modify",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "read-only",
      "read-write",
      "read-write-plaintext-only",
    ]
  },
  {
    property: "-webkit-user-select",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "element",
    ]
  },
  {
    property: "scroll-behavior",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "smooth",
    ]
  },
  {
    property: "-webkit-overflow-scrolling",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "touch",
    ]
  },
  {
    property: "touch-action",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "none",
      "manipulation",
      "pan-x",
      "pan-y",
      "pinch-zoom",
    ]
  },
  {
    property: "-webkit-touch-callout",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "default",
      "none",
    ]
  },
  {
    property: "-apple-trailing-word",
    values: [
      "initial",
      "inherit",
      "unset",
      "revert",
      "revert-layer",
      "auto",
      "-webkit-partially-balanced",
    ]
  }
]

export default declarations;
